# The URL the site will be built for
base_url = "https://blog.dark-flames.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "apollo"

taxonomies = [{ name = "tags", feed = true }]


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
menu = [
  { name = "/posts", url = "/posts", weight = 1 },
  { name = "/tags", url = "/tags", weight = 2 },
  { name = "/about", url = "/about", weight = 3 },
]

socials = [
  { name = "twitter", url = "https://twitter.com/Darkf1ames", icon = "twitter" },
  { name = "github", url = "https://github.com/dark-flames", icon = "github" },
]

insert_anchor_links = "heading"

dynamic_note = true
